---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: money-lit-relay
  namespace: money-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: money-lit-relay
  template:
    metadata:
      labels:
        app: money-lit-relay
    spec:
      containers:
        - name: relay-server
          image: 646978790787.dkr.ecr.us-east-1.amazonaws.com/money-lit-relay:0.3
          ports:
            - containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: env
              mountPath: '/app/.env'
              subPath: 'env'
              readOnly: true
      volumes:
        - name: env
          configMap:
            name: money-lit-relay-config
            items:
              - key: 'env'
                path: 'env'
